# Generated by Django 4.2.7 on 2023-12-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorUsers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=10)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('actividad', models.CharField(max_length=100)),
            ],
        ),
    ]
