# Generated by Django 4.2.7 on 2023-12-19 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestorUsers', '0002_horario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_trabajador', models.CharField(max_length=12)),
                ('nombre_trabajador', models.CharField(max_length=55)),
                ('apellido_trabajador', models.CharField(max_length=55)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(max_length=55)),
                ('direccion', models.CharField(max_length=55)),
                ('fecha_inicio_contrato', models.DateField()),
                ('fecha_termino_contrato', models.DateField()),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestorUsers.area')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestorUsers.cargo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestorUsers.empresa')),
                ('tipo_contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestorUsers.tipocontrato')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestorUsers.usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='Horario',
        ),
        migrations.DeleteModel(
            name='Seccion',
        ),
    ]
