# Generated by Django 4.2.7 on 2023-12-19 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestorUsers', '0003_trabajador_delete_horario_delete_seccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tarea', models.CharField(max_length=55)),
                ('descripcion_tarea', models.TextField(blank=True, max_length=500)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestorUsers.trabajador')),
            ],
        ),
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_solicitud', models.CharField(max_length=55)),
                ('descripcion_solicitud', models.TextField(blank=True, max_length=500)),
                ('fecha_inicio', models.DateField()),
                ('fecha_termino', models.DateField()),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestorUsers.trabajador')),
            ],
        ),
    ]
